"use strict";
var express = require('express');
var morgan = require('morgan');
var bodyParser = require('body-parser');
var api = express();
var routes = require('./routes/routes')();
api.use(morgan('dev'));
api.use(bodyParser.urlencoded({ extended: true }));
api.use(bodyParser.json());
routes(api);
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = api;
