"use strict";
var express = require('express');
var morgan = require('morgan');
var bodyParser = require('body-parser');
var api = express();
var routes = require('./routes/routes')();
api.use(morgan('dev'));
api.use(bodyParser.urlencoded({ extended: true }));
api.use(bodyParser.json());
routes(api);
exports.__esModule = true;
exports["default"] = api;
